// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments_has_customer_overlap_excluding_appointment.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const hasCustomerOverlapExcludingAppointment = `-- name: HasCustomerOverlapExcludingAppointment :one
SELECT EXISTS (
    SELECT 1
    FROM appointments a
    WHERE a.tenant_id = $1
      AND a.customer_id = $2
      AND a.id <> $3
      AND a.status NOT IN ('cancelled', 'no_show')
      AND a.starts_at < $4
      AND a.ends_at > $5
) AS has_overlap
`

type HasCustomerOverlapExcludingAppointmentParams struct {
	TenantID              uuid.UUID `db:"tenant_id"`
	CustomerID            uuid.UUID `db:"customer_id"`
	ExcludedAppointmentID uuid.UUID `db:"excluded_appointment_id"`
	EndsAt                time.Time `db:"ends_at"`
	StartsAt              time.Time `db:"starts_at"`
}

// HasCustomerOverlapExcludingAppointment
//
//	SELECT EXISTS (
//	    SELECT 1
//	    FROM appointments a
//	    WHERE a.tenant_id = $1
//	      AND a.customer_id = $2
//	      AND a.id <> $3
//	      AND a.status NOT IN ('cancelled', 'no_show')
//	      AND a.starts_at < $4
//	      AND a.ends_at > $5
//	) AS has_overlap
func (q *Queries) HasCustomerOverlapExcludingAppointment(ctx context.Context, db DBTX, arg HasCustomerOverlapExcludingAppointmentParams) (bool, error) {
	row := db.QueryRowContext(ctx, hasCustomerOverlapExcludingAppointment,
		arg.TenantID,
		arg.CustomerID,
		arg.ExcludedAppointmentID,
		arg.EndsAt,
		arg.StartsAt,
	)
	var has_overlap bool
	err := row.Scan(&has_overlap)
	return has_overlap, err
}
