// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_field_responses_insert.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertAppointmentFieldResponse = `-- name: InsertAppointmentFieldResponse :exec
INSERT INTO appointment_field_responses (
    id,
    appointment_id,
    field_key,
    response
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (appointment_id, field_key) DO UPDATE
SET response = EXCLUDED.response
`

type InsertAppointmentFieldResponseParams struct {
	ID            uuid.UUID `db:"id"`
	AppointmentID uuid.UUID `db:"appointment_id"`
	FieldKey      string    `db:"field_key"`
	Response      string    `db:"response"`
}

// InsertAppointmentFieldResponse
//
//	INSERT INTO appointment_field_responses (
//	    id,
//	    appointment_id,
//	    field_key,
//	    response
//	)
//	VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4
//	)
//	ON CONFLICT (appointment_id, field_key) DO UPDATE
//	SET response = EXCLUDED.response
func (q *Queries) InsertAppointmentFieldResponse(ctx context.Context, db DBTX, arg InsertAppointmentFieldResponseParams) error {
	_, err := db.ExecContext(ctx, insertAppointmentFieldResponse,
		arg.ID,
		arg.AppointmentID,
		arg.FieldKey,
		arg.Response,
	)
	return err
}
