// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments_find_by_resource_in_range.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findResourceAppointmentsInRange = `-- name: FindResourceAppointmentsInRange :many
SELECT a.id,
       a.starts_at,
       a.ends_at,
       COALESCE(c.name, '') AS customer_name,
       s.name               AS service_name
FROM appointments a
         INNER JOIN customers c ON c.id = a.customer_id
         INNER JOIN services s ON s.id = a.service_id
WHERE a.resource_id = $1
  AND a.starts_at < $2
  AND a.ends_at > $3
  AND a.status NOT IN ('cancelled', 'no_show')
ORDER BY a.starts_at
`

type FindResourceAppointmentsInRangeParams struct {
	ResourceID uuid.UUID `db:"resource_id"`
	RangeEnd   time.Time `db:"range_end"`
	RangeStart time.Time `db:"range_start"`
}

type FindResourceAppointmentsInRangeRow struct {
	ID           uuid.UUID `db:"id"`
	StartsAt     time.Time `db:"starts_at"`
	EndsAt       time.Time `db:"ends_at"`
	CustomerName string    `db:"customer_name"`
	ServiceName  string    `db:"service_name"`
}

// FindResourceAppointmentsInRange
//
//	SELECT a.id,
//	       a.starts_at,
//	       a.ends_at,
//	       COALESCE(c.name, '') AS customer_name,
//	       s.name               AS service_name
//	FROM appointments a
//	         INNER JOIN customers c ON c.id = a.customer_id
//	         INNER JOIN services s ON s.id = a.service_id
//	WHERE a.resource_id = $1
//	  AND a.starts_at < $2
//	  AND a.ends_at > $3
//	  AND a.status NOT IN ('cancelled', 'no_show')
//	ORDER BY a.starts_at
func (q *Queries) FindResourceAppointmentsInRange(ctx context.Context, db DBTX, arg FindResourceAppointmentsInRangeParams) ([]FindResourceAppointmentsInRangeRow, error) {
	rows, err := db.QueryContext(ctx, findResourceAppointmentsInRange, arg.ResourceID, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindResourceAppointmentsInRangeRow
	for rows.Next() {
		var i FindResourceAppointmentsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.CustomerName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
