// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments_count_upcoming_by_resource.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUpcomingAppointmentsByResource = `-- name: CountUpcomingAppointmentsByResource :one
SELECT count(*)
FROM appointments
WHERE resource_id = $1
  AND status IN ('pending', 'confirmed', 'check_in', 'in_progress')
  AND ends_at > now()
`

// Appointments that still need the resource: every status that can still
// happen, limited to those not yet over so stale rows nobody closed do not
// block deletion forever.
//
//	SELECT count(*)
//	FROM appointments
//	WHERE resource_id = $1
//	  AND status IN ('pending', 'confirmed', 'check_in', 'in_progress')
//	  AND ends_at > now()
func (q *Queries) CountUpcomingAppointmentsByResource(ctx context.Context, db DBTX, resourceID uuid.UUID) (int64, error) {
	row := db.QueryRowContext(ctx, countUpcomingAppointmentsByResource, resourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
