// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments_reschedule.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const rescheduleAppointment = `-- name: RescheduleAppointment :execrows
UPDATE appointments
SET starts_at             = $1,
    ends_at               = $2,
    reminder_24h_sent_at  = NULL,
    reminder_1h_sent_at   = NULL,
    updated_at            = NOW()
WHERE id = $3
  AND tenant_id = $4
  AND customer_id = $5
  AND status = 'confirmed'::appointment_status
`

type RescheduleAppointmentParams struct {
	StartsAt   time.Time `db:"starts_at"`
	EndsAt     time.Time `db:"ends_at"`
	ID         uuid.UUID `db:"id"`
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
}

// RescheduleAppointment
//
//	UPDATE appointments
//	SET starts_at             = $1,
//	    ends_at               = $2,
//	    reminder_24h_sent_at  = NULL,
//	    reminder_1h_sent_at   = NULL,
//	    updated_at            = NOW()
//	WHERE id = $3
//	  AND tenant_id = $4
//	  AND customer_id = $5
//	  AND status = 'confirmed'::appointment_status
func (q *Queries) RescheduleAppointment(ctx context.Context, db DBTX, arg RescheduleAppointmentParams) (int64, error) {
	result, err := db.ExecContext(ctx, rescheduleAppointment,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
