// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_field_responses_find_latest_one_time.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const findLatestOneTimeFlowFieldAnswers = `-- name: FindLatestOneTimeFlowFieldAnswers :many
SELECT DISTINCT ON (afr.field_key)
       afr.field_key,
       afr.response
FROM appointment_field_responses afr
JOIN appointments a ON a.id = afr.appointment_id
WHERE a.tenant_id = $1
  AND a.customer_id = $2
  AND afr.field_key = ANY($3::text[])
ORDER BY afr.field_key, afr.created_at DESC
`

type FindLatestOneTimeFlowFieldAnswersParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
	FieldKeys  []string  `db:"field_keys"`
}

type FindLatestOneTimeFlowFieldAnswersRow struct {
	FieldKey string `db:"field_key"`
	Response string `db:"response"`
}

// FindLatestOneTimeFlowFieldAnswers
//
//	SELECT DISTINCT ON (afr.field_key)
//	       afr.field_key,
//	       afr.response
//	FROM appointment_field_responses afr
//	JOIN appointments a ON a.id = afr.appointment_id
//	WHERE a.tenant_id = $1
//	  AND a.customer_id = $2
//	  AND afr.field_key = ANY($3::text[])
//	ORDER BY afr.field_key, afr.created_at DESC
func (q *Queries) FindLatestOneTimeFlowFieldAnswers(ctx context.Context, db DBTX, arg FindLatestOneTimeFlowFieldAnswersParams) ([]FindLatestOneTimeFlowFieldAnswersRow, error) {
	rows, err := db.QueryContext(ctx, findLatestOneTimeFlowFieldAnswers, arg.TenantID, arg.CustomerID, pq.Array(arg.FieldKeys))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindLatestOneTimeFlowFieldAnswersRow
	for rows.Next() {
		var i FindLatestOneTimeFlowFieldAnswersRow
		if err := rows.Scan(&i.FieldKey, &i.Response); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
