// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments_count_upcoming_by_service.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUpcomingAppointmentsByService = `-- name: CountUpcomingAppointmentsByService :one
SELECT count(*)
FROM appointments
WHERE service_id = $1
  AND status IN ('pending', 'confirmed', 'check_in', 'in_progress')
  AND ends_at > now()
`

// Same rule as CountUpcomingAppointmentsByResource, keyed by service.
//
//	SELECT count(*)
//	FROM appointments
//	WHERE service_id = $1
//	  AND status IN ('pending', 'confirmed', 'check_in', 'in_progress')
//	  AND ends_at > now()
func (q *Queries) CountUpcomingAppointmentsByService(ctx context.Context, db DBTX, serviceID uuid.UUID) (int64, error) {
	row := db.QueryRowContext(ctx, countUpcomingAppointmentsByService, serviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
