// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_sessions_insert_when_inactive.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertConversationSessionWhenInactive = `-- name: InsertConversationSessionWhenInactive :execrows
INSERT INTO conversation_sessions(
    id,
    tenant_id,
    whatsapp_config_id,
    customer_id,
    step,
    data,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) ON CONFLICT (tenant_id, customer_id) DO UPDATE
    SET step       = EXCLUDED.step,
        data       = EXCLUDED.data,
        expires_at = EXCLUDED.expires_at,
        updated_at = NOW()
    WHERE conversation_sessions.expires_at <= NOW()
`

type InsertConversationSessionWhenInactiveParams struct {
	ID               uuid.UUID       `db:"id"`
	TenantID         uuid.UUID       `db:"tenant_id"`
	WhatsappConfigID uuid.UUID       `db:"whatsapp_config_id"`
	CustomerID       uuid.UUID       `db:"customer_id"`
	Step             string          `db:"step"`
	Data             json.RawMessage `db:"data"`
	ExpiresAt        time.Time       `db:"expires_at"`
}

// InsertConversationSessionWhenInactive
//
//	INSERT INTO conversation_sessions(
//	    id,
//	    tenant_id,
//	    whatsapp_config_id,
//	    customer_id,
//	    step,
//	    data,
//	    expires_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7
//	) ON CONFLICT (tenant_id, customer_id) DO UPDATE
//	    SET step       = EXCLUDED.step,
//	        data       = EXCLUDED.data,
//	        expires_at = EXCLUDED.expires_at,
//	        updated_at = NOW()
//	    WHERE conversation_sessions.expires_at <= NOW()
func (q *Queries) InsertConversationSessionWhenInactive(ctx context.Context, db DBTX, arg InsertConversationSessionWhenInactiveParams) (int64, error) {
	result, err := db.ExecContext(ctx, insertConversationSessionWhenInactive,
		arg.ID,
		arg.TenantID,
		arg.WhatsappConfigID,
		arg.CustomerID,
		arg.Step,
		arg.Data,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
