// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers_search.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const searchCustomers = `-- name: SearchCustomers :many
SELECT id,
       phone_number,
       name,
       is_blocked,
       no_show_count,
       late_cancel_count
FROM customers
WHERE tenant_id = $1
  AND ($2::text IS NULL
    OR strpos(regexp_replace(normalize(lower(name), NFD), '[\u0300-\u036f]', '', 'g'),
              regexp_replace(normalize(lower($2::text), NFD), '[\u0300-\u036f]', '', 'g')) > 0)
  AND ($3::text IS NULL
    OR strpos(regexp_replace(phone_number, '\D', '', 'g'), $3::text) > 0)
  AND ($4::boolean IS NULL OR is_blocked = $4::boolean)
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type SearchCustomersParams struct {
	TenantID    uuid.UUID      `db:"tenant_id"`
	Name        sql.NullString `db:"name"`
	PhoneDigits sql.NullString `db:"phone_digits"`
	IsBlocked   sql.NullBool   `db:"is_blocked"`
	PageOffset  int32          `db:"page_offset"`
	PageLimit   int32          `db:"page_limit"`
}

type SearchCustomersRow struct {
	ID              uuid.UUID      `db:"id"`
	PhoneNumber     string         `db:"phone_number"`
	Name            sql.NullString `db:"name"`
	IsBlocked       bool           `db:"is_blocked"`
	NoShowCount     int32          `db:"no_show_count"`
	LateCancelCount int32          `db:"late_cancel_count"`
}

// Filters are optional: a NULL argument disables its condition. Name matching
// folds case and strips every diacritic (NFD, then drop combining marks), so
// "jose" finds "José" and "munoz" finds "Muñoz". Phone matching runs on bare
// digits so callers can search by any fragment of the number.
//
//	SELECT id,
//	       phone_number,
//	       name,
//	       is_blocked,
//	       no_show_count,
//	       late_cancel_count
//	FROM customers
//	WHERE tenant_id = $1
//	  AND ($2::text IS NULL
//	    OR strpos(regexp_replace(normalize(lower(name), NFD), '[\u0300-\u036f]', '', 'g'),
//	              regexp_replace(normalize(lower($2::text), NFD), '[\u0300-\u036f]', '', 'g')) > 0)
//	  AND ($3::text IS NULL
//	    OR strpos(regexp_replace(phone_number, '\D', '', 'g'), $3::text) > 0)
//	  AND ($4::boolean IS NULL OR is_blocked = $4::boolean)
//	ORDER BY created_at DESC, id DESC
//	LIMIT $6 OFFSET $5
func (q *Queries) SearchCustomers(ctx context.Context, db DBTX, arg SearchCustomersParams) ([]SearchCustomersRow, error) {
	rows, err := db.QueryContext(ctx, searchCustomers,
		arg.TenantID,
		arg.Name,
		arg.PhoneDigits,
		arg.IsBlocked,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCustomersRow
	for rows.Next() {
		var i SearchCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.Name,
			&i.IsBlocked,
			&i.NoShowCount,
			&i.LateCancelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
