// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers_count_search.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countSearchCustomers = `-- name: CountSearchCustomers :one
SELECT count(*)
FROM customers
WHERE tenant_id = $1
  AND ($2::text IS NULL
    OR strpos(translate(lower(name), 'áéíóúüàèìòù', 'aeiouuaeiou'),
              translate(lower($2::text), 'áéíóúüàèìòù', 'aeiouuaeiou')) > 0)
  AND ($3::text IS NULL
    OR strpos(regexp_replace(phone_number, '\D', '', 'g'), $3::text) > 0)
  AND ($4::boolean IS NULL OR is_blocked = $4::boolean)
`

type CountSearchCustomersParams struct {
	TenantID    uuid.UUID      `db:"tenant_id"`
	Name        sql.NullString `db:"name"`
	PhoneDigits sql.NullString `db:"phone_digits"`
	IsBlocked   sql.NullBool   `db:"is_blocked"`
}

// Must apply exactly the same filters as SearchCustomers.
//
//	SELECT count(*)
//	FROM customers
//	WHERE tenant_id = $1
//	  AND ($2::text IS NULL
//	    OR strpos(translate(lower(name), 'áéíóúüàèìòù', 'aeiouuaeiou'),
//	              translate(lower($2::text), 'áéíóúüàèìòù', 'aeiouuaeiou')) > 0)
//	  AND ($3::text IS NULL
//	    OR strpos(regexp_replace(phone_number, '\D', '', 'g'), $3::text) > 0)
//	  AND ($4::boolean IS NULL OR is_blocked = $4::boolean)
func (q *Queries) CountSearchCustomers(ctx context.Context, db DBTX, arg CountSearchCustomersParams) (int64, error) {
	row := db.QueryRowContext(ctx, countSearchCustomers,
		arg.TenantID,
		arg.Name,
		arg.PhoneDigits,
		arg.IsBlocked,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
