// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_events_renew_claim.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const renewDomainEventClaim = `-- name: RenewDomainEventClaim :execrows
UPDATE domain_events
SET claimed_at = NOW()
WHERE claim_id = $1::uuid
  AND processed_at IS NULL
  AND failed_at IS NULL
`

// RenewDomainEventClaim
//
//	UPDATE domain_events
//	SET claimed_at = NOW()
//	WHERE claim_id = $1::uuid
//	  AND processed_at IS NULL
//	  AND failed_at IS NULL
func (q *Queries) RenewDomainEventClaim(ctx context.Context, db DBTX, claimID uuid.UUID) (int64, error) {
	result, err := db.ExecContext(ctx, renewDomainEventClaim, claimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
