// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_events_mark_failed.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markDomainEventFailed = `-- name: MarkDomainEventFailed :execrows
UPDATE domain_events
SET attempts   = attempts + 1,
    claimed_at = NULL,
    claim_id    = NULL,
    last_error = $1,
    failed_at  = CASE WHEN attempts + 1 >= 5 THEN NOW() ELSE NULL END
WHERE id = $2
  AND claim_id = $3::uuid
  AND processed_at IS NULL
`

type MarkDomainEventFailedParams struct {
	LastError sql.NullString `db:"last_error"`
	ID        uuid.UUID      `db:"id"`
	ClaimID   uuid.UUID      `db:"claim_id"`
}

// MarkDomainEventFailed
//
//	UPDATE domain_events
//	SET attempts   = attempts + 1,
//	    claimed_at = NULL,
//	    claim_id    = NULL,
//	    last_error = $1,
//	    failed_at  = CASE WHEN attempts + 1 >= 5 THEN NOW() ELSE NULL END
//	WHERE id = $2
//	  AND claim_id = $3::uuid
//	  AND processed_at IS NULL
func (q *Queries) MarkDomainEventFailed(ctx context.Context, db DBTX, arg MarkDomainEventFailedParams) (int64, error) {
	result, err := db.ExecContext(ctx, markDomainEventFailed, arg.LastError, arg.ID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
