// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_events_mark_failed.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markDomainEventFailed = `-- name: MarkDomainEventFailed :exec
UPDATE domain_events
SET attempts   = attempts + 1,
    claimed_at = NULL,
    last_error = $2,
    failed_at  = CASE WHEN attempts + 1 >= 5 THEN NOW() ELSE NULL END
WHERE id = $1
  AND processed_at IS NULL
`

type MarkDomainEventFailedParams struct {
	ID        uuid.UUID      `db:"id"`
	LastError sql.NullString `db:"last_error"`
}

// MarkDomainEventFailed
//
//	UPDATE domain_events
//	SET attempts   = attempts + 1,
//	    claimed_at = NULL,
//	    last_error = $2,
//	    failed_at  = CASE WHEN attempts + 1 >= 5 THEN NOW() ELSE NULL END
//	WHERE id = $1
//	  AND processed_at IS NULL
func (q *Queries) MarkDomainEventFailed(ctx context.Context, db DBTX, arg MarkDomainEventFailedParams) error {
	_, err := db.ExecContext(ctx, markDomainEventFailed, arg.ID, arg.LastError)
	return err
}
