// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_event_handler_completions_find.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findCompletedDomainEventHandlers = `-- name: FindCompletedDomainEventHandlers :many
SELECT handler_id
FROM domain_event_handler_completions
WHERE event_id = $1
`

// FindCompletedDomainEventHandlers
//
//	SELECT handler_id
//	FROM domain_event_handler_completions
//	WHERE event_id = $1
func (q *Queries) FindCompletedDomainEventHandlers(ctx context.Context, db DBTX, eventID uuid.UUID) ([]string, error) {
	rows, err := db.QueryContext(ctx, findCompletedDomainEventHandlers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var handler_id string
		if err := rows.Scan(&handler_id); err != nil {
			return nil, err
		}
		items = append(items, handler_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
