// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_events_insert.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertDomainEvent = `-- name: InsertDomainEvent :exec
INSERT INTO domain_events (id, tenant_id, event_type, payload)
VALUES ($1, $2, $3, $4)
`

type InsertDomainEventParams struct {
	ID        uuid.UUID       `db:"id"`
	TenantID  uuid.UUID       `db:"tenant_id"`
	EventType string          `db:"event_type"`
	Payload   json.RawMessage `db:"payload"`
}

// InsertDomainEvent
//
//	INSERT INTO domain_events (id, tenant_id, event_type, payload)
//	VALUES ($1, $2, $3, $4)
func (q *Queries) InsertDomainEvent(ctx context.Context, db DBTX, arg InsertDomainEventParams) error {
	_, err := db.ExecContext(ctx, insertDomainEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.Payload,
	)
	return err
}
