// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_events_claim_pending.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimPendingDomainEvents = `-- name: ClaimPendingDomainEvents :many
SELECT id, tenant_id, event_type, payload, attempts, created_at
FROM domain_events
WHERE processed_at IS NULL
  AND failed_at IS NULL
  AND attempts < 5
ORDER BY created_at
LIMIT 100
FOR UPDATE SKIP LOCKED
`

type ClaimPendingDomainEventsRow struct {
	ID        uuid.UUID       `db:"id"`
	TenantID  uuid.UUID       `db:"tenant_id"`
	EventType string          `db:"event_type"`
	Payload   json.RawMessage `db:"payload"`
	Attempts  int32           `db:"attempts"`
	CreatedAt time.Time       `db:"created_at"`
}

// ClaimPendingDomainEvents
//
//	SELECT id, tenant_id, event_type, payload, attempts, created_at
//	FROM domain_events
//	WHERE processed_at IS NULL
//	  AND failed_at IS NULL
//	  AND attempts < 5
//	ORDER BY created_at
//	LIMIT 100
//	FOR UPDATE SKIP LOCKED
func (q *Queries) ClaimPendingDomainEvents(ctx context.Context, db DBTX) ([]ClaimPendingDomainEventsRow, error) {
	rows, err := db.QueryContext(ctx, claimPendingDomainEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingDomainEventsRow
	for rows.Next() {
		var i ClaimPendingDomainEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
