// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_event_handler_completions_insert.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertDomainEventHandlerCompletion = `-- name: InsertDomainEventHandlerCompletion :exec
INSERT INTO domain_event_handler_completions (event_id, handler_id)
VALUES ($1, $2)
ON CONFLICT (event_id, handler_id) DO NOTHING
`

type InsertDomainEventHandlerCompletionParams struct {
	EventID   uuid.UUID `db:"event_id"`
	HandlerID string    `db:"handler_id"`
}

// InsertDomainEventHandlerCompletion
//
//	INSERT INTO domain_event_handler_completions (event_id, handler_id)
//	VALUES ($1, $2)
//	ON CONFLICT (event_id, handler_id) DO NOTHING
func (q *Queries) InsertDomainEventHandlerCompletion(ctx context.Context, db DBTX, arg InsertDomainEventHandlerCompletionParams) error {
	_, err := db.ExecContext(ctx, insertDomainEventHandlerCompletion, arg.EventID, arg.HandlerID)
	return err
}
