// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_events_claim_pending.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const claimPendingDomainEvents = `-- name: ClaimPendingDomainEvents :many
UPDATE domain_events
SET claimed_at = NOW(),
    claim_id   = $1::uuid
WHERE id IN (
    SELECT id
    FROM domain_events
    WHERE processed_at IS NULL
      AND failed_at IS NULL
      AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '10 minutes')
      AND attempts < 5
      AND NOT (id = ANY($2::uuid[]))
    ORDER BY created_at
    LIMIT 100
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, event_type, payload, attempts, created_at
`

type ClaimPendingDomainEventsParams struct {
	ClaimID     uuid.UUID   `db:"claim_id"`
	ExcludedIds []uuid.UUID `db:"excluded_ids"`
}

type ClaimPendingDomainEventsRow struct {
	ID        uuid.UUID       `db:"id"`
	TenantID  uuid.UUID       `db:"tenant_id"`
	EventType string          `db:"event_type"`
	Payload   json.RawMessage `db:"payload"`
	Attempts  int32           `db:"attempts"`
	CreatedAt time.Time       `db:"created_at"`
}

// ClaimPendingDomainEvents
//
//	UPDATE domain_events
//	SET claimed_at = NOW(),
//	    claim_id   = $1::uuid
//	WHERE id IN (
//	    SELECT id
//	    FROM domain_events
//	    WHERE processed_at IS NULL
//	      AND failed_at IS NULL
//	      AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '10 minutes')
//	      AND attempts < 5
//	      AND NOT (id = ANY($2::uuid[]))
//	    ORDER BY created_at
//	    LIMIT 100
//	    FOR UPDATE SKIP LOCKED
//	)
//	RETURNING id, tenant_id, event_type, payload, attempts, created_at
func (q *Queries) ClaimPendingDomainEvents(ctx context.Context, db DBTX, arg ClaimPendingDomainEventsParams) ([]ClaimPendingDomainEventsRow, error) {
	rows, err := db.QueryContext(ctx, claimPendingDomainEvents, arg.ClaimID, pq.Array(arg.ExcludedIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingDomainEventsRow
	for rows.Next() {
		var i ClaimPendingDomainEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
