// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_events_mark_processed.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const markDomainEventProcessed = `-- name: MarkDomainEventProcessed :exec
UPDATE domain_events
SET claimed_at   = NULL,
    processed_at = NOW()
WHERE id = $1
`

// MarkDomainEventProcessed
//
//	UPDATE domain_events
//	SET claimed_at   = NULL,
//	    processed_at = NOW()
//	WHERE id = $1
func (q *Queries) MarkDomainEventProcessed(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.ExecContext(ctx, markDomainEventProcessed, id)
	return err
}
