// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AppointmentStatus string

const (
	AppointmentStatusPending    AppointmentStatus = "pending"
	AppointmentStatusConfirmed  AppointmentStatus = "confirmed"
	AppointmentStatusInProgress AppointmentStatus = "in_progress"
	AppointmentStatusCompleted  AppointmentStatus = "completed"
	AppointmentStatusCancelled  AppointmentStatus = "cancelled"
	AppointmentStatusNoShow     AppointmentStatus = "no_show"
	AppointmentStatusCheckIn    AppointmentStatus = "check_in"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus
	Valid             bool // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type FlowFieldType string

const (
	FlowFieldTypePredefined FlowFieldType = "predefined"
	FlowFieldTypeCustom     FlowFieldType = "custom"
)

func (e *FlowFieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlowFieldType(s)
	case string:
		*e = FlowFieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for FlowFieldType: %T", src)
	}
	return nil
}

type NullFlowFieldType struct {
	FlowFieldType FlowFieldType
	Valid         bool // Valid is true if FlowFieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlowFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.FlowFieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlowFieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlowFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlowFieldType), nil
}

type WhatsappActivationStatus string

const (
	WhatsappActivationStatusPending    WhatsappActivationStatus = "pending"
	WhatsappActivationStatusInProgress WhatsappActivationStatus = "in_progress"
	WhatsappActivationStatusActive     WhatsappActivationStatus = "active"
	WhatsappActivationStatusFailed     WhatsappActivationStatus = "failed"
)

func (e *WhatsappActivationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhatsappActivationStatus(s)
	case string:
		*e = WhatsappActivationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WhatsappActivationStatus: %T", src)
	}
	return nil
}

type NullWhatsappActivationStatus struct {
	WhatsappActivationStatus WhatsappActivationStatus
	Valid                    bool // Valid is true if WhatsappActivationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhatsappActivationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WhatsappActivationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhatsappActivationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhatsappActivationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhatsappActivationStatus), nil
}

type Account struct {
	AccessToken           sql.NullString `db:"access_token"`
	AccessTokenExpiresAt  sql.NullTime   `db:"access_token_expires_at"`
	AccountID             string         `db:"account_id"`
	CreatedAt             time.Time      `db:"created_at"`
	ID                    string         `db:"id"`
	IDToken               sql.NullString `db:"id_token"`
	Password              sql.NullString `db:"password"`
	ProviderID            string         `db:"provider_id"`
	RefreshToken          sql.NullString `db:"refresh_token"`
	RefreshTokenExpiresAt sql.NullTime   `db:"refresh_token_expires_at"`
	Scope                 sql.NullString `db:"scope"`
	UpdatedAt             time.Time      `db:"updated_at"`
	UserID                string         `db:"user_id"`
}

type Appointment struct {
	ID                uuid.UUID         `db:"id"`
	TenantID          uuid.UUID         `db:"tenant_id"`
	ResourceID        uuid.UUID         `db:"resource_id"`
	ServiceID         uuid.UUID         `db:"service_id"`
	CustomerID        uuid.UUID         `db:"customer_id"`
	StartsAt          time.Time         `db:"starts_at"`
	EndsAt            time.Time         `db:"ends_at"`
	Status            AppointmentStatus `db:"status"`
	CancelledBy       sql.NullString    `db:"cancelled_by"`
	CancelReason      sql.NullString    `db:"cancel_reason"`
	PriceAtBooking    string            `db:"price_at_booking"`
	Reminder24hSentAt sql.NullTime      `db:"reminder_24h_sent_at"`
	Reminder1hSentAt  sql.NullTime      `db:"reminder_1h_sent_at"`
	Notes             sql.NullString    `db:"notes"`
	CreatedAt         time.Time         `db:"created_at"`
	UpdatedAt         time.Time         `db:"updated_at"`
	CancelledAt       sql.NullTime      `db:"cancelled_at"`
	CompletedAt       sql.NullTime      `db:"completed_at"`
}

type AppointmentFieldResponse struct {
	ID            uuid.UUID `db:"id"`
	AppointmentID uuid.UUID `db:"appointment_id"`
	FieldKey      string    `db:"field_key"`
	Response      string    `db:"response"`
	CreatedAt     time.Time `db:"created_at"`
}

type AppointmentPenaltyEvent struct {
	ID            uuid.UUID `db:"id"`
	AppointmentID uuid.UUID `db:"appointment_id"`
	TenantID      uuid.UUID `db:"tenant_id"`
	CustomerID    uuid.UUID `db:"customer_id"`
	EventType     string    `db:"event_type"`
	OccurredAt    time.Time `db:"occurred_at"`
	CreatedAt     time.Time `db:"created_at"`
}

type AppointmentReminderEvent struct {
	ID            uuid.UUID      `db:"id"`
	AppointmentID uuid.UUID      `db:"appointment_id"`
	TenantID      uuid.UUID      `db:"tenant_id"`
	CustomerID    uuid.UUID      `db:"customer_id"`
	ReminderType  string         `db:"reminder_type"`
	Attempts      int32          `db:"attempts"`
	SentAt        sql.NullTime   `db:"sent_at"`
	LastAttemptAt sql.NullTime   `db:"last_attempt_at"`
	LastError     sql.NullString `db:"last_error"`
	CreatedAt     time.Time      `db:"created_at"`
}

type AppointmentStatusHistory struct {
	ID            uuid.UUID         `db:"id"`
	AppointmentID uuid.UUID         `db:"appointment_id"`
	FromStatus    AppointmentStatus `db:"from_status"`
	ToStatus      AppointmentStatus `db:"to_status"`
	ChangedBy     sql.NullString    `db:"changed_by"`
	ChangedByRole sql.NullString    `db:"changed_by_role"`
	Reason        sql.NullString    `db:"reason"`
	CreatedAt     time.Time         `db:"created_at"`
}

type ConversationSession struct {
	ID               uuid.UUID       `db:"id"`
	TenantID         uuid.UUID       `db:"tenant_id"`
	WhatsappConfigID uuid.UUID       `db:"whatsapp_config_id"`
	CustomerID       uuid.UUID       `db:"customer_id"`
	Step             string          `db:"step"`
	Data             json.RawMessage `db:"data"`
	ExpiresAt        time.Time       `db:"expires_at"`
	CreatedAt        time.Time       `db:"created_at"`
	UpdatedAt        time.Time       `db:"updated_at"`
}

type Customer struct {
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
	PhoneNumber     string         `db:"phone_number"`
	Name            sql.NullString `db:"name"`
	IsBlocked       bool           `db:"is_blocked"`
	CreatedAt       time.Time      `db:"created_at"`
	NoShowCount     int32          `db:"no_show_count"`
	LateCancelCount int32          `db:"late_cancel_count"`
	DocumentId      sql.NullString `db:"documentId"`
	BirthDate       sql.NullTime   `db:"birth_date"`
	Email           sql.NullString `db:"email"`
	Address         sql.NullString `db:"address"`
}

type DomainEvent struct {
	ID          uuid.UUID       `db:"id"`
	TenantID    uuid.UUID       `db:"tenant_id"`
	EventType   string          `db:"event_type"`
	Payload     json.RawMessage `db:"payload"`
	Attempts    int32           `db:"attempts"`
	ClaimedAt   sql.NullTime    `db:"claimed_at"`
	ClaimID     uuid.NullUUID   `db:"claim_id"`
	ProcessedAt sql.NullTime    `db:"processed_at"`
	FailedAt    sql.NullTime    `db:"failed_at"`
	LastError   sql.NullString  `db:"last_error"`
	CreatedAt   time.Time       `db:"created_at"`
}

type DomainEventHandlerCompletion struct {
	EventID     uuid.UUID `db:"event_id"`
	HandlerID   string    `db:"handler_id"`
	CompletedAt time.Time `db:"completed_at"`
}

type Jwk struct {
	CreatedAt  time.Time    `db:"created_at"`
	ExpiresAt  sql.NullTime `db:"expires_at"`
	ID         string       `db:"id"`
	PrivateKey string       `db:"private_key"`
	PublicKey  string       `db:"public_key"`
}

type OnboardingProgress struct {
	ID          uuid.UUID    `db:"id"`
	TenantID    uuid.UUID    `db:"tenant_id"`
	CurrentStep int32        `db:"current_step"`
	CompletedAt sql.NullTime `db:"completed_at"`
	CreatedAt   time.Time    `db:"created_at"`
	UpdatedAt   time.Time    `db:"updated_at"`
}

type Plan struct {
	ID              uuid.UUID       `db:"id"`
	ExternalID      string          `db:"external_id"`
	ExternalPriceID sql.NullString  `db:"external_price_id"`
	Name            string          `db:"name"`
	Description     sql.NullString  `db:"description"`
	Price           int32           `db:"price"`
	Currency        string          `db:"currency"`
	Interval        sql.NullString  `db:"interval"`
	Features        json.RawMessage `db:"features"`
	IsActive        bool            `db:"is_active"`
	CreatedAt       time.Time       `db:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at"`
	Environment     string          `db:"environment"`
}

type Resource struct {
	ID        uuid.UUID      `db:"id"`
	TenantID  uuid.UUID      `db:"tenant_id"`
	Name      string         `db:"name"`
	Type      string         `db:"type"`
	AvatarUrl sql.NullString `db:"avatar_url"`
	IsActive  bool           `db:"is_active"`
	SortOrder int32          `db:"sort_order"`
	CreatedAt time.Time      `db:"created_at"`
}

type ResourceService struct {
	ResourceID uuid.UUID `db:"resource_id"`
	ServiceID  uuid.UUID `db:"service_id"`
}

type ScheduleOverride struct {
	ID         uuid.UUID      `db:"id"`
	ResourceID uuid.UUID      `db:"resource_id"`
	Date       time.Time      `db:"date"`
	IsDayOff   bool           `db:"is_day_off"`
	StartTime  sql.NullString `db:"start_time"`
	EndTime    sql.NullString `db:"end_time"`
	Reason     sql.NullString `db:"reason"`
	CreatedAt  time.Time      `db:"created_at"`
}

type Service struct {
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
	Name            string         `db:"name"`
	Description     sql.NullString `db:"description"`
	DurationMinutes int32          `db:"duration_minutes"`
	BufferMinutes   int32          `db:"buffer_minutes"`
	Price           string         `db:"price"`
	IsActive        bool           `db:"is_active"`
	SortOrder       int32          `db:"sort_order"`
	CreatedAt       time.Time      `db:"created_at"`
}

type Session struct {
	CreatedAt      time.Time      `db:"created_at"`
	ExpiresAt      time.Time      `db:"expires_at"`
	ID             string         `db:"id"`
	IpAddress      sql.NullString `db:"ip_address"`
	Token          string         `db:"token"`
	UpdatedAt      time.Time      `db:"updated_at"`
	UserAgent      sql.NullString `db:"user_agent"`
	UserID         string         `db:"user_id"`
	ImpersonatedBy sql.NullString `db:"impersonated_by"`
}

type Subscription struct {
	ID                 uuid.UUID    `db:"id"`
	TenantID           uuid.UUID    `db:"tenant_id"`
	PlanID             uuid.UUID    `db:"plan_id"`
	ExternalID         string       `db:"external_id"`
	ExternalCustomerID string       `db:"external_customer_id"`
	Status             string       `db:"status"`
	CurrentPeriodStart sql.NullTime `db:"current_period_start"`
	CurrentPeriodEnd   sql.NullTime `db:"current_period_end"`
	CancelAtPeriodEnd  bool         `db:"cancel_at_period_end"`
	CanceledAt         sql.NullTime `db:"canceled_at"`
	CreatedAt          time.Time    `db:"created_at"`
	UpdatedAt          time.Time    `db:"updated_at"`
	Environment        string       `db:"environment"`
}

type SubscriptionOrder struct {
	ID             uuid.UUID `db:"id"`
	SubscriptionID uuid.UUID `db:"subscription_id"`
	ExternalID     string    `db:"external_id"`
	Amount         int32     `db:"amount"`
	Currency       string    `db:"currency"`
	Status         string    `db:"status"`
	CreatedAt      time.Time `db:"created_at"`
	Environment    string    `db:"environment"`
}

type Tenant struct {
	ID                    uuid.UUID `db:"id"`
	Name                  string    `db:"name"`
	Slug                  string    `db:"slug"`
	Timezone              string    `db:"timezone"`
	Currency              string    `db:"currency"`
	AppointmentsThisMonth int32     `db:"appointments_this_month"`
	MonthResetAt          time.Time `db:"month_reset_at"`
	IsActive              bool      `db:"is_active"`
	Settings              []byte    `db:"settings"`
	CreatedAt             time.Time `db:"created_at"`
	UpdatedAt             time.Time `db:"updated_at"`
}

type TenantFlowField struct {
	ID         uuid.UUID      `db:"id"`
	TenantID   uuid.UUID      `db:"tenant_id"`
	FieldKey   string         `db:"field_key"`
	FieldType  FlowFieldType  `db:"field_type"`
	Question   sql.NullString `db:"question"`
	IsRequired bool           `db:"is_required"`
	IsOneTime  bool           `db:"is_one_time"`
	IsEnabled  bool           `db:"is_enabled"`
	SortOrder  int32          `db:"sort_order"`
	CreatedAt  time.Time      `db:"created_at"`
}

type TenantUser struct {
	UserID   string    `db:"user_id"`
	TenantID uuid.UUID `db:"tenant_id"`
	Role     string    `db:"role"`
}

type TenantWhatsappConfig struct {
	ID                     uuid.UUID                `db:"id"`
	TenantID               uuid.UUID                `db:"tenant_id"`
	WabaID                 sql.NullString           `db:"waba_id"`
	PhoneNumberID          sql.NullString           `db:"phone_number_id"`
	DisplayPhoneNumber     sql.NullString           `db:"display_phone_number"`
	AccessToken            sql.NullString           `db:"access_token"`
	TokenExpiresAt         sql.NullTime             `db:"token_expires_at"`
	IsActive               bool                     `db:"is_active"`
	VerifiedAt             sql.NullTime             `db:"verified_at"`
	CreatedAt              time.Time                `db:"created_at"`
	UpdatedAt              time.Time                `db:"updated_at"`
	ActivationStatus       WhatsappActivationStatus `db:"activation_status"`
	ActivationRequestedAt  sql.NullTime             `db:"activation_requested_at"`
	ActivationNotes        sql.NullString           `db:"activation_notes"`
	ActivationContactEmail sql.NullString           `db:"activation_contact_email"`
	RejectReason           sql.NullString           `db:"reject_reason"`
}

type User struct {
	CreatedAt     time.Time      `db:"created_at"`
	Email         string         `db:"email"`
	EmailVerified bool           `db:"email_verified"`
	ID            string         `db:"id"`
	Image         sql.NullString `db:"image"`
	Name          string         `db:"name"`
	UpdatedAt     time.Time      `db:"updated_at"`
	BanExpires    sql.NullTime   `db:"ban_expires"`
	BanReason     sql.NullString `db:"ban_reason"`
	Banned        sql.NullBool   `db:"banned"`
	Role          sql.NullString `db:"role"`
}

type Verification struct {
	CreatedAt  time.Time `db:"created_at"`
	ExpiresAt  time.Time `db:"expires_at"`
	ID         string    `db:"id"`
	Identifier string    `db:"identifier"`
	UpdatedAt  time.Time `db:"updated_at"`
	Value      string    `db:"value"`
}

type WorkingHour struct {
	ID         uuid.UUID `db:"id"`
	ResourceID uuid.UUID `db:"resource_id"`
	DayOfWeek  int16     `db:"day_of_week"`
	StartTime  time.Time `db:"start_time"`
	EndTime    time.Time `db:"end_time"`
	IsActive   bool      `db:"is_active"`
}
