// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_count_active_by_tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActiveResourcesByTenant = `-- name: CountActiveResourcesByTenant :one
SELECT count(*)
FROM resources
WHERE tenant_id = $1
  AND is_active = true
`

// Deleted resources are soft-deleted (is_active = false) and must not use
// up plan quota. Aggregates without GROUP BY so a tenant with no resources
// yields 0 instead of no rows.
//
//	SELECT count(*)
//	FROM resources
//	WHERE tenant_id = $1
//	  AND is_active = true
func (q *Queries) CountActiveResourcesByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) (int64, error) {
	row := db.QueryRowContext(ctx, countActiveResourcesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
