// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_find_by_service_id.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findResourcesByServiceID = `-- name: FindResourcesByServiceID :many
SELECT r.id,
       r.tenant_id,
       r.name,
       r.type,
       COALESCE(r.avatar_url, '') as avatar_url,
       r.is_active,
       r.sort_order,
       r.created_at
FROM resources r
         JOIN resource_services rs ON rs.resource_id = r.id
WHERE r.tenant_id = $1
  AND rs.service_id = $2
  AND r.is_active = true
  AND r.deleted_at IS NULL
ORDER BY r.created_at
`

type FindResourcesByServiceIDParams struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	ServiceID uuid.UUID `db:"service_id"`
}

type FindResourcesByServiceIDRow struct {
	ID        uuid.UUID `db:"id"`
	TenantID  uuid.UUID `db:"tenant_id"`
	Name      string    `db:"name"`
	Type      string    `db:"type"`
	AvatarUrl string    `db:"avatar_url"`
	IsActive  bool      `db:"is_active"`
	SortOrder int32     `db:"sort_order"`
	CreatedAt time.Time `db:"created_at"`
}

// FindResourcesByServiceID
//
//	SELECT r.id,
//	       r.tenant_id,
//	       r.name,
//	       r.type,
//	       COALESCE(r.avatar_url, '') as avatar_url,
//	       r.is_active,
//	       r.sort_order,
//	       r.created_at
//	FROM resources r
//	         JOIN resource_services rs ON rs.resource_id = r.id
//	WHERE r.tenant_id = $1
//	  AND rs.service_id = $2
//	  AND r.is_active = true
//	  AND r.deleted_at IS NULL
//	ORDER BY r.created_at
func (q *Queries) FindResourcesByServiceID(ctx context.Context, db DBTX, arg FindResourcesByServiceIDParams) ([]FindResourcesByServiceIDRow, error) {
	rows, err := db.QueryContext(ctx, findResourcesByServiceID, arg.TenantID, arg.ServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindResourcesByServiceIDRow
	for rows.Next() {
		var i FindResourcesByServiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.AvatarUrl,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
