// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateResource = `-- name: UpdateResource :exec
UPDATE resources
SET name       = $1,
    type       = $2,
    avatar_url = $3,
    is_active  = $4
WHERE id = $5
  AND tenant_id = $6
`

type UpdateResourceParams struct {
	Name      string         `db:"name"`
	Type      string         `db:"type"`
	AvatarUrl sql.NullString `db:"avatar_url"`
	IsActive  bool           `db:"is_active"`
	ID        uuid.UUID      `db:"id"`
	TenantID  uuid.UUID      `db:"tenant_id"`
}

// sort_order is owned by the resources_update_sort_order route; writing it
// here would reset the order whenever a client edits the resource details.
//
//	UPDATE resources
//	SET name       = $1,
//	    type       = $2,
//	    avatar_url = $3,
//	    is_active  = $4
//	WHERE id = $5
//	  AND tenant_id = $6
func (q *Queries) UpdateResource(ctx context.Context, db DBTX, arg UpdateResourceParams) error {
	_, err := db.ExecContext(ctx, updateResource,
		arg.Name,
		arg.Type,
		arg.AvatarUrl,
		arg.IsActive,
		arg.ID,
		arg.TenantID,
	)
	return err
}
