// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_services_find_bookable_by_tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findBookableResourceServicesByTenant = `-- name: FindBookableResourceServicesByTenant :many
SELECT r.id AS resource_id,
       r.name AS resource_name,
       COALESCE(r.avatar_url, '') AS resource_avatar_url,
       rs.service_id
FROM resources r
         JOIN resource_services rs ON rs.resource_id = r.id
         JOIN services s ON s.id = rs.service_id AND s.is_active = true
WHERE r.tenant_id = $1
  AND r.is_active = true
ORDER BY r.sort_order, r.created_at, rs.service_id
`

type FindBookableResourceServicesByTenantRow struct {
	ResourceID        uuid.UUID `db:"resource_id"`
	ResourceName      string    `db:"resource_name"`
	ResourceAvatarUrl string    `db:"resource_avatar_url"`
	ServiceID         uuid.UUID `db:"service_id"`
}

// FindBookableResourceServicesByTenant
//
//	SELECT r.id AS resource_id,
//	       r.name AS resource_name,
//	       COALESCE(r.avatar_url, '') AS resource_avatar_url,
//	       rs.service_id
//	FROM resources r
//	         JOIN resource_services rs ON rs.resource_id = r.id
//	         JOIN services s ON s.id = rs.service_id AND s.is_active = true
//	WHERE r.tenant_id = $1
//	  AND r.is_active = true
//	ORDER BY r.sort_order, r.created_at, rs.service_id
func (q *Queries) FindBookableResourceServicesByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]FindBookableResourceServicesByTenantRow, error) {
	rows, err := db.QueryContext(ctx, findBookableResourceServicesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindBookableResourceServicesByTenantRow
	for rows.Next() {
		var i FindBookableResourceServicesByTenantRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceName,
			&i.ResourceAvatarUrl,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
