// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_lock_live.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const lockLiveResource = `-- name: LockLiveResource :one
SELECT id
FROM resources
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
FOR SHARE
`

type LockLiveResourceParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// Takes a share lock on a live resource for the rest of the transaction.
// Deletion updates the row, so it waits for transactions holding this lock
// and then sees their appointments; a transaction that locks after a
// committed deletion gets no row.
//
//	SELECT id
//	FROM resources
//	WHERE id = $1
//	  AND tenant_id = $2
//	  AND deleted_at IS NULL
//	FOR SHARE
func (q *Queries) LockLiveResource(ctx context.Context, db DBTX, arg LockLiveResourceParams) (uuid.UUID, error) {
	row := db.QueryRowContext(ctx, lockLiveResource, arg.ID, arg.TenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
