// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_services_insert_for_tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const insertResourceServicesForTenant = `-- name: InsertResourceServicesForTenant :execrows
INSERT INTO resource_services (resource_id, service_id)
SELECT $1::uuid, s.id
FROM services s
WHERE s.id = ANY ($2::uuid[])
  AND s.tenant_id = $3
  AND s.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type InsertResourceServicesForTenantParams struct {
	ResourceID uuid.UUID   `db:"resource_id"`
	ServiceIds []uuid.UUID `db:"service_ids"`
	TenantID   uuid.UUID   `db:"tenant_id"`
}

// Links only services owned by the tenant that are not deleted, so a client
// cannot attach another tenant's service to its resource. Each matching
// service yields one row, so the affected count equals the number of distinct
// valid ids; a smaller count means some ids were rejected.
//
//	INSERT INTO resource_services (resource_id, service_id)
//	SELECT $1::uuid, s.id
//	FROM services s
//	WHERE s.id = ANY ($2::uuid[])
//	  AND s.tenant_id = $3
//	  AND s.deleted_at IS NULL
//	ON CONFLICT DO NOTHING
func (q *Queries) InsertResourceServicesForTenant(ctx context.Context, db DBTX, arg InsertResourceServicesForTenantParams) (int64, error) {
	result, err := db.ExecContext(ctx, insertResourceServicesForTenant, arg.ResourceID, pq.Array(arg.ServiceIds), arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
