// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteResource = `-- name: DeleteResource :execrows
UPDATE resources
SET deleted_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type DeleteResourceParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// Zero affected rows means the resource does not exist, belongs to another
// tenant or is already deleted.
//
//	UPDATE resources
//	SET deleted_at = now()
//	WHERE id = $1
//	  AND tenant_id = $2
//	  AND deleted_at IS NULL
func (q *Queries) DeleteResource(ctx context.Context, db DBTX, arg DeleteResourceParams) (int64, error) {
	result, err := db.ExecContext(ctx, deleteResource, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
