// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_find_by_tenant.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findResourcesByTenant = `-- name: FindResourcesByTenant :many
SELECT id,
       tenant_id,
       name,
       type,
       COALESCE(avatar_url, '') as avatar_url,
       is_active,
       sort_order,
       created_at
FROM resources
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at
`

type FindResourcesByTenantRow struct {
	ID        uuid.UUID `db:"id"`
	TenantID  uuid.UUID `db:"tenant_id"`
	Name      string    `db:"name"`
	Type      string    `db:"type"`
	AvatarUrl string    `db:"avatar_url"`
	IsActive  bool      `db:"is_active"`
	SortOrder int32     `db:"sort_order"`
	CreatedAt time.Time `db:"created_at"`
}

// FindResourcesByTenant
//
//	SELECT id,
//	       tenant_id,
//	       name,
//	       type,
//	       COALESCE(avatar_url, '') as avatar_url,
//	       is_active,
//	       sort_order,
//	       created_at
//	FROM resources
//	WHERE tenant_id = $1
//	  AND deleted_at IS NULL
//	ORDER BY created_at
func (q *Queries) FindResourcesByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]FindResourcesByTenantRow, error) {
	rows, err := db.QueryContext(ctx, findResourcesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindResourcesByTenantRow
	for rows.Next() {
		var i FindResourcesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.AvatarUrl,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
