// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_find_by_id.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findResourceById = `-- name: FindResourceById :one
SELECT id,
       tenant_id,
       name,
       type,
       COALESCE(avatar_url, '') as avatar_url,
       is_active,
       sort_order,
       created_at,
       deleted_at
FROM resources
WHERE id = $1
LIMIT 1
`

type FindResourceByIdRow struct {
	ID        uuid.UUID    `db:"id"`
	TenantID  uuid.UUID    `db:"tenant_id"`
	Name      string       `db:"name"`
	Type      string       `db:"type"`
	AvatarUrl string       `db:"avatar_url"`
	IsActive  bool         `db:"is_active"`
	SortOrder int32        `db:"sort_order"`
	CreatedAt time.Time    `db:"created_at"`
	DeletedAt sql.NullTime `db:"deleted_at"`
}

// FindResourceById
//
//	SELECT id,
//	       tenant_id,
//	       name,
//	       type,
//	       COALESCE(avatar_url, '') as avatar_url,
//	       is_active,
//	       sort_order,
//	       created_at,
//	       deleted_at
//	FROM resources
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) FindResourceById(ctx context.Context, db DBTX, id uuid.UUID) (FindResourceByIdRow, error) {
	row := db.QueryRowContext(ctx, findResourceById, id)
	var i FindResourceByIdRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.AvatarUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
