// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_count_by_tenant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countResourcesByTenant = `-- name: CountResourcesByTenant :one
SELECT count(*)
FROM resources
WHERE tenant_id = $1
  AND deleted_at IS NULL
`

// Deleted resources must not use up plan quota. Inactive ones still do:
// is_active only pauses scheduling, and toggling it must not free a slot.
// Aggregates without GROUP BY so a tenant with no resources yields 0
// instead of no rows.
//
//	SELECT count(*)
//	FROM resources
//	WHERE tenant_id = $1
//	  AND deleted_at IS NULL
func (q *Queries) CountResourcesByTenant(ctx context.Context, db DBTX, tenantID uuid.UUID) (int64, error) {
	row := db.QueryRowContext(ctx, countResourcesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
