// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_overrides_insert.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertScheduleOverride = `-- name: InsertScheduleOverride :exec
INSERT INTO schedule_overrides(
    id,
    resource_id,
    start_date,
    end_date,
    kind,
    start_time,
    end_time,
    reason
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertScheduleOverrideParams struct {
	ID         uuid.UUID            `db:"id"`
	ResourceID uuid.UUID            `db:"resource_id"`
	StartDate  time.Time            `db:"start_date"`
	EndDate    time.Time            `db:"end_date"`
	Kind       ScheduleOverrideKind `db:"kind"`
	StartTime  sql.NullString       `db:"start_time"`
	EndTime    sql.NullString       `db:"end_time"`
	Reason     sql.NullString       `db:"reason"`
}

// InsertScheduleOverride
//
//	INSERT INTO schedule_overrides(
//	    id,
//	    resource_id,
//	    start_date,
//	    end_date,
//	    kind,
//	    start_time,
//	    end_time,
//	    reason
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8
//	)
func (q *Queries) InsertScheduleOverride(ctx context.Context, db DBTX, arg InsertScheduleOverrideParams) error {
	_, err := db.ExecContext(ctx, insertScheduleOverride,
		arg.ID,
		arg.ResourceID,
		arg.StartDate,
		arg.EndDate,
		arg.Kind,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	return err
}
