// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_overrides_find_by_resource.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findResourceScheduleOverrides = `-- name: FindResourceScheduleOverrides :many
SELECT id,
       resource_id,
       start_date,
       end_date,
       kind,
       start_time,
       end_time,
       COALESCE(reason, '') as reason,
       created_at
FROM schedule_overrides
WHERE resource_id = $1
  AND start_date <= $2
  AND end_date >= $3
ORDER BY start_date
`

type FindResourceScheduleOverridesParams struct {
	ResourceID uuid.UUID `db:"resource_id"`
	ToDate     time.Time `db:"to_date"`
	FromDate   time.Time `db:"from_date"`
}

type FindResourceScheduleOverridesRow struct {
	ID         uuid.UUID            `db:"id"`
	ResourceID uuid.UUID            `db:"resource_id"`
	StartDate  time.Time            `db:"start_date"`
	EndDate    time.Time            `db:"end_date"`
	Kind       ScheduleOverrideKind `db:"kind"`
	StartTime  sql.NullString       `db:"start_time"`
	EndTime    sql.NullString       `db:"end_time"`
	Reason     string               `db:"reason"`
	CreatedAt  time.Time            `db:"created_at"`
}

// FindResourceScheduleOverrides
//
//	SELECT id,
//	       resource_id,
//	       start_date,
//	       end_date,
//	       kind,
//	       start_time,
//	       end_time,
//	       COALESCE(reason, '') as reason,
//	       created_at
//	FROM schedule_overrides
//	WHERE resource_id = $1
//	  AND start_date <= $2
//	  AND end_date >= $3
//	ORDER BY start_date
func (q *Queries) FindResourceScheduleOverrides(ctx context.Context, db DBTX, arg FindResourceScheduleOverridesParams) ([]FindResourceScheduleOverridesRow, error) {
	rows, err := db.QueryContext(ctx, findResourceScheduleOverrides, arg.ResourceID, arg.ToDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindResourceScheduleOverridesRow
	for rows.Next() {
		var i FindResourceScheduleOverridesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.StartDate,
			&i.EndDate,
			&i.Kind,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
