// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services_find_by_id_including_inactive.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findServiceByIDIncludingInactive = `-- name: FindServiceByIDIncludingInactive :one
SELECT id,
       tenant_id,
       name,
       description,
       duration_minutes,
       buffer_minutes,
       price,
       is_active,
       sort_order,
       created_at,
       deleted_at
FROM services
WHERE id = $1
`

// An existing appointment can point at a service the owner has since paused
// or deleted, so this returns both. Use this when describing what was already
// booked; use FindServiceByID when the service must still be bookable.
//
//	SELECT id,
//	       tenant_id,
//	       name,
//	       description,
//	       duration_minutes,
//	       buffer_minutes,
//	       price,
//	       is_active,
//	       sort_order,
//	       created_at,
//	       deleted_at
//	FROM services
//	WHERE id = $1
func (q *Queries) FindServiceByIDIncludingInactive(ctx context.Context, db DBTX, id uuid.UUID) (Service, error) {
	row := db.QueryRowContext(ctx, findServiceByIDIncludingInactive, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
