// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateService = `-- name: UpdateService :execrows
UPDATE services
SET name             = $1,
    description      = $2,
    duration_minutes = $3,
    buffer_minutes   = $4,
    price            = $5,
    is_active        = $6
WHERE id = $7
  AND tenant_id = $8
  AND deleted_at IS NULL
`

type UpdateServiceParams struct {
	Name            string         `db:"name"`
	Description     sql.NullString `db:"description"`
	DurationMinutes int32          `db:"duration_minutes"`
	BufferMinutes   int32          `db:"buffer_minutes"`
	Price           string         `db:"price"`
	IsActive        bool           `db:"is_active"`
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
}

// sort_order is not written here: no route owns service ordering yet, and
// writing a fixed value would reset it on every edit.
// Deleted services are excluded so an edit racing a delete cannot modify the
// row; zero affected rows means the service is gone.
//
//	UPDATE services
//	SET name             = $1,
//	    description      = $2,
//	    duration_minutes = $3,
//	    buffer_minutes   = $4,
//	    price            = $5,
//	    is_active        = $6
//	WHERE id = $7
//	  AND tenant_id = $8
//	  AND deleted_at IS NULL
func (q *Queries) UpdateService(ctx context.Context, db DBTX, arg UpdateServiceParams) (int64, error) {
	result, err := db.ExecContext(ctx, updateService,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.Price,
		arg.IsActive,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
