// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services_lock_live.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const lockLiveService = `-- name: LockLiveService :one
SELECT id
FROM services
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
FOR SHARE
`

type LockLiveServiceParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// Service counterpart of LockLiveResource.
//
//	SELECT id
//	FROM services
//	WHERE id = $1
//	  AND tenant_id = $2
//	  AND deleted_at IS NULL
//	FOR SHARE
func (q *Queries) LockLiveService(ctx context.Context, db DBTX, arg LockLiveServiceParams) (uuid.UUID, error) {
	row := db.QueryRowContext(ctx, lockLiveService, arg.ID, arg.TenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
