// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteService = `-- name: DeleteService :execrows
UPDATE services
SET deleted_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type DeleteServiceParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// is_active is the owner's pause switch, so deletion is tracked separately.
// Already deleted rows are skipped so the original deletion time is kept;
// zero affected rows means the service is gone.
//
//	UPDATE services
//	SET deleted_at = now()
//	WHERE id = $1
//	  AND tenant_id = $2
//	  AND deleted_at IS NULL
func (q *Queries) DeleteService(ctx context.Context, db DBTX, arg DeleteServiceParams) (int64, error) {
	result, err := db.ExecContext(ctx, deleteService, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
