// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services_find_by_id.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findServiceByID = `-- name: FindServiceByID :one
SELECT id,
       tenant_id,
       name,
       description,
       duration_minutes,
       buffer_minutes,
       price,
       is_active,
       sort_order,
       created_at,
       deleted_at
FROM services
WHERE id = $1
  AND is_active = true
  AND deleted_at IS NULL
`

// FindServiceByID
//
//	SELECT id,
//	       tenant_id,
//	       name,
//	       description,
//	       duration_minutes,
//	       buffer_minutes,
//	       price,
//	       is_active,
//	       sort_order,
//	       created_at,
//	       deleted_at
//	FROM services
//	WHERE id = $1
//	  AND is_active = true
//	  AND deleted_at IS NULL
func (q *Queries) FindServiceByID(ctx context.Context, db DBTX, id uuid.UUID) (Service, error) {
	row := db.QueryRowContext(ctx, findServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
