// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants_update_appointment_count.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const incrementTenantAppointmentCount = `-- name: IncrementTenantAppointmentCount :execrows
UPDATE tenants
SET appointments_this_month = appointments_this_month + 1,
    updated_at              = NOW()
WHERE id = $1
  AND (
    $2::int IS NULL
        OR appointments_this_month < $2::int
    )
`

type IncrementTenantAppointmentCountParams struct {
	ID                      uuid.UUID     `db:"id"`
	MaxAppointmentsPerMonth sql.NullInt32 `db:"max_appointments_per_month"`
}

// IncrementTenantAppointmentCount
//
//	UPDATE tenants
//	SET appointments_this_month = appointments_this_month + 1,
//	    updated_at              = NOW()
//	WHERE id = $1
//	  AND (
//	    $2::int IS NULL
//	        OR appointments_this_month < $2::int
//	    )
func (q *Queries) IncrementTenantAppointmentCount(ctx context.Context, db DBTX, arg IncrementTenantAppointmentCountParams) (int64, error) {
	result, err := db.ExecContext(ctx, incrementTenantAppointmentCount, arg.ID, arg.MaxAppointmentsPerMonth)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
