// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_flow_fields_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateFlowField = `-- name: UpdateFlowField :execrows
UPDATE tenant_flow_fields
SET question    = $3,
    is_required = $4,
    is_one_time = $5,
    sort_order  = $6
WHERE id = $1
  AND tenant_id = $2
`

type UpdateFlowFieldParams struct {
	ID         uuid.UUID      `db:"id"`
	TenantID   uuid.UUID      `db:"tenant_id"`
	Question   sql.NullString `db:"question"`
	IsRequired bool           `db:"is_required"`
	IsOneTime  bool           `db:"is_one_time"`
	SortOrder  int32          `db:"sort_order"`
}

// UpdateFlowField
//
//	UPDATE tenant_flow_fields
//	SET question    = $3,
//	    is_required = $4,
//	    is_one_time = $5,
//	    sort_order  = $6
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) UpdateFlowField(ctx context.Context, db DBTX, arg UpdateFlowFieldParams) (int64, error) {
	result, err := db.ExecContext(ctx, updateFlowField,
		arg.ID,
		arg.TenantID,
		arg.Question,
		arg.IsRequired,
		arg.IsOneTime,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
