// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_flow_fields_insert.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertTenantFlowField = `-- name: InsertTenantFlowField :one
INSERT INTO tenant_flow_fields (
    id,
    tenant_id,
    field_key,
    question,
    field_type,
    min_length,
    max_length,
    min_value,
    max_value,
    is_required,
    is_one_time,
    is_enabled,
    sort_order
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    true,
    $12
)
RETURNING id,
          field_key,
          question,
          field_type,
          min_length,
          max_length,
          min_value,
          max_value,
          is_required,
          is_one_time,
          is_enabled,
          sort_order
`

type InsertTenantFlowFieldParams struct {
	ID         uuid.UUID     `db:"id"`
	TenantID   uuid.UUID     `db:"tenant_id"`
	FieldKey   string        `db:"field_key"`
	Question   string        `db:"question"`
	FieldType  FlowFieldType `db:"field_type"`
	MinLength  sql.NullInt16 `db:"min_length"`
	MaxLength  sql.NullInt16 `db:"max_length"`
	MinValue   sql.NullInt32 `db:"min_value"`
	MaxValue   sql.NullInt32 `db:"max_value"`
	IsRequired bool          `db:"is_required"`
	IsOneTime  bool          `db:"is_one_time"`
	SortOrder  int32         `db:"sort_order"`
}

type InsertTenantFlowFieldRow struct {
	ID         uuid.UUID     `db:"id"`
	FieldKey   string        `db:"field_key"`
	Question   string        `db:"question"`
	FieldType  FlowFieldType `db:"field_type"`
	MinLength  sql.NullInt16 `db:"min_length"`
	MaxLength  sql.NullInt16 `db:"max_length"`
	MinValue   sql.NullInt32 `db:"min_value"`
	MaxValue   sql.NullInt32 `db:"max_value"`
	IsRequired bool          `db:"is_required"`
	IsOneTime  bool          `db:"is_one_time"`
	IsEnabled  bool          `db:"is_enabled"`
	SortOrder  int32         `db:"sort_order"`
}

// InsertTenantFlowField
//
//	INSERT INTO tenant_flow_fields (
//	    id,
//	    tenant_id,
//	    field_key,
//	    question,
//	    field_type,
//	    min_length,
//	    max_length,
//	    min_value,
//	    max_value,
//	    is_required,
//	    is_one_time,
//	    is_enabled,
//	    sort_order
//	)
//	VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    true,
//	    $12
//	)
//	RETURNING id,
//	          field_key,
//	          question,
//	          field_type,
//	          min_length,
//	          max_length,
//	          min_value,
//	          max_value,
//	          is_required,
//	          is_one_time,
//	          is_enabled,
//	          sort_order
func (q *Queries) InsertTenantFlowField(ctx context.Context, db DBTX, arg InsertTenantFlowFieldParams) (InsertTenantFlowFieldRow, error) {
	row := db.QueryRowContext(ctx, insertTenantFlowField,
		arg.ID,
		arg.TenantID,
		arg.FieldKey,
		arg.Question,
		arg.FieldType,
		arg.MinLength,
		arg.MaxLength,
		arg.MinValue,
		arg.MaxValue,
		arg.IsRequired,
		arg.IsOneTime,
		arg.SortOrder,
	)
	var i InsertTenantFlowFieldRow
	err := row.Scan(
		&i.ID,
		&i.FieldKey,
		&i.Question,
		&i.FieldType,
		&i.MinLength,
		&i.MaxLength,
		&i.MinValue,
		&i.MaxValue,
		&i.IsRequired,
		&i.IsOneTime,
		&i.IsEnabled,
		&i.SortOrder,
	)
	return i, err
}
