// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants_lock_for_quota.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const lockTenantForQuota = `-- name: LockTenantForQuota :one
SELECT id
FROM tenants
WHERE id = $1
FOR NO KEY UPDATE
`

// Serialises quota checks for a tenant until the caller's transaction ends.
// NO KEY UPDATE conflicts with itself but not with the KEY SHARE locks that
// foreign-key inserts take, so unrelated writes for the tenant still proceed.
//
//	SELECT id
//	FROM tenants
//	WHERE id = $1
//	FOR NO KEY UPDATE
func (q *Queries) LockTenantForQuota(ctx context.Context, db DBTX, id uuid.UUID) (uuid.UUID, error) {
	row := db.QueryRowContext(ctx, lockTenantForQuota, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}
