// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants_insert.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertTenant = `-- name: InsertTenant :execrows
INSERT INTO tenants(
    id,
    name,
    slug,
    timezone,
    currency,
    appointments_this_month,
    month_reset_at,
    is_active,
    settings
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    0,
    $6,
    true,
    $7
)
ON CONFLICT (slug) DO NOTHING
`

type InsertTenantParams struct {
	ID           uuid.UUID `db:"id"`
	Name         string    `db:"name"`
	Slug         string    `db:"slug"`
	Timezone     string    `db:"timezone"`
	Currency     string    `db:"currency"`
	MonthResetAt time.Time `db:"month_reset_at"`
	Settings     []byte    `db:"settings"`
}

// A taken slug inserts nothing (0 rows) instead of raising, so callers can
// retry with another slug inside the same transaction; a unique violation
// would abort it.
//
//	INSERT INTO tenants(
//	    id,
//	    name,
//	    slug,
//	    timezone,
//	    currency,
//	    appointments_this_month,
//	    month_reset_at,
//	    is_active,
//	    settings
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    0,
//	    $6,
//	    true,
//	    $7
//	)
//	ON CONFLICT (slug) DO NOTHING
func (q *Queries) InsertTenant(ctx context.Context, db DBTX, arg InsertTenantParams) (int64, error) {
	result, err := db.ExecContext(ctx, insertTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Timezone,
		arg.Currency,
		arg.MonthResetAt,
		arg.Settings,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
