// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants_find_owner_email.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findTenantOwnerEmail = `-- name: FindTenantOwnerEmail :one
SELECT u.email
FROM tenant_users tu
         JOIN users u ON u.id = tu.user_id
WHERE tu.tenant_id = $1
  AND tu.role = 'admin'
ORDER BY tu.user_id
LIMIT 1
`

// FindTenantOwnerEmail
//
//	SELECT u.email
//	FROM tenant_users tu
//	         JOIN users u ON u.id = tu.user_id
//	WHERE tu.tenant_id = $1
//	  AND tu.role = 'admin'
//	ORDER BY tu.user_id
//	LIMIT 1
func (q *Queries) FindTenantOwnerEmail(ctx context.Context, db DBTX, tenantID uuid.UUID) (string, error) {
	row := db.QueryRowContext(ctx, findTenantOwnerEmail, tenantID)
	var email string
	err := row.Scan(&email)
	return email, err
}
