// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_flow_fields_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateFlowField = `-- name: UpdateFlowField :execrows
UPDATE tenant_flow_fields
SET question    = $3,
    field_type  = $4,
    min_length  = $5,
    max_length  = $6,
    min_value   = $7,
    max_value   = $8,
    is_required = $9,
    is_one_time = $10,
    sort_order  = $11
WHERE id = $1
  AND tenant_id = $2
`

type UpdateFlowFieldParams struct {
	ID         uuid.UUID     `db:"id"`
	TenantID   uuid.UUID     `db:"tenant_id"`
	Question   string        `db:"question"`
	FieldType  FlowFieldType `db:"field_type"`
	MinLength  sql.NullInt16 `db:"min_length"`
	MaxLength  sql.NullInt16 `db:"max_length"`
	MinValue   sql.NullInt32 `db:"min_value"`
	MaxValue   sql.NullInt32 `db:"max_value"`
	IsRequired bool          `db:"is_required"`
	IsOneTime  bool          `db:"is_one_time"`
	SortOrder  int32         `db:"sort_order"`
}

// UpdateFlowField
//
//	UPDATE tenant_flow_fields
//	SET question    = $3,
//	    field_type  = $4,
//	    min_length  = $5,
//	    max_length  = $6,
//	    min_value   = $7,
//	    max_value   = $8,
//	    is_required = $9,
//	    is_one_time = $10,
//	    sort_order  = $11
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) UpdateFlowField(ctx context.Context, db DBTX, arg UpdateFlowFieldParams) (int64, error) {
	result, err := db.ExecContext(ctx, updateFlowField,
		arg.ID,
		arg.TenantID,
		arg.Question,
		arg.FieldType,
		arg.MinLength,
		arg.MaxLength,
		arg.MinValue,
		arg.MaxValue,
		arg.IsRequired,
		arg.IsOneTime,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
