// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_flow_fields_find_enabled.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findTenantEnabledFlowFields = `-- name: FindTenantEnabledFlowFields :many
SELECT id,
       field_key,
       question,
       field_type,
       min_length,
       max_length,
       min_value,
       max_value,
       is_required,
       is_one_time,
       sort_order
FROM tenant_flow_fields
WHERE tenant_id = $1
  AND is_enabled = true
ORDER BY sort_order, created_at
`

type FindTenantEnabledFlowFieldsRow struct {
	ID         uuid.UUID     `db:"id"`
	FieldKey   string        `db:"field_key"`
	Question   string        `db:"question"`
	FieldType  FlowFieldType `db:"field_type"`
	MinLength  sql.NullInt16 `db:"min_length"`
	MaxLength  sql.NullInt16 `db:"max_length"`
	MinValue   sql.NullInt32 `db:"min_value"`
	MaxValue   sql.NullInt32 `db:"max_value"`
	IsRequired bool          `db:"is_required"`
	IsOneTime  bool          `db:"is_one_time"`
	SortOrder  int32         `db:"sort_order"`
}

// FindTenantEnabledFlowFields
//
//	SELECT id,
//	       field_key,
//	       question,
//	       field_type,
//	       min_length,
//	       max_length,
//	       min_value,
//	       max_value,
//	       is_required,
//	       is_one_time,
//	       sort_order
//	FROM tenant_flow_fields
//	WHERE tenant_id = $1
//	  AND is_enabled = true
//	ORDER BY sort_order, created_at
func (q *Queries) FindTenantEnabledFlowFields(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]FindTenantEnabledFlowFieldsRow, error) {
	rows, err := db.QueryContext(ctx, findTenantEnabledFlowFields, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindTenantEnabledFlowFieldsRow
	for rows.Next() {
		var i FindTenantEnabledFlowFieldsRow
		if err := rows.Scan(
			&i.ID,
			&i.FieldKey,
			&i.Question,
			&i.FieldType,
			&i.MinLength,
			&i.MaxLength,
			&i.MinValue,
			&i.MaxValue,
			&i.IsRequired,
			&i.IsOneTime,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
