// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_flow_fields_insert_custom.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertCustomTenantFlowField = `-- name: InsertCustomTenantFlowField :one
INSERT INTO tenant_flow_fields (
    id,
    tenant_id,
    field_key,
    field_type,
    question,
    is_required,
    is_enabled,
    sort_order
)
VALUES (
    $1,
    $2,
    $3,
    'custom',
    $4,
    $5,
    true,
    $6
)
RETURNING id,
          field_key,
          field_type,
          question,
          is_required,
          is_enabled,
          sort_order
`

type InsertCustomTenantFlowFieldParams struct {
	ID         uuid.UUID      `db:"id"`
	TenantID   uuid.UUID      `db:"tenant_id"`
	FieldKey   string         `db:"field_key"`
	Question   sql.NullString `db:"question"`
	IsRequired bool           `db:"is_required"`
	SortOrder  int32          `db:"sort_order"`
}

type InsertCustomTenantFlowFieldRow struct {
	ID         uuid.UUID      `db:"id"`
	FieldKey   string         `db:"field_key"`
	FieldType  FlowFieldType  `db:"field_type"`
	Question   sql.NullString `db:"question"`
	IsRequired bool           `db:"is_required"`
	IsEnabled  bool           `db:"is_enabled"`
	SortOrder  int32          `db:"sort_order"`
}

// InsertCustomTenantFlowField
//
//	INSERT INTO tenant_flow_fields (
//	    id,
//	    tenant_id,
//	    field_key,
//	    field_type,
//	    question,
//	    is_required,
//	    is_enabled,
//	    sort_order
//	)
//	VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    'custom',
//	    $4,
//	    $5,
//	    true,
//	    $6
//	)
//	RETURNING id,
//	          field_key,
//	          field_type,
//	          question,
//	          is_required,
//	          is_enabled,
//	          sort_order
func (q *Queries) InsertCustomTenantFlowField(ctx context.Context, db DBTX, arg InsertCustomTenantFlowFieldParams) (InsertCustomTenantFlowFieldRow, error) {
	row := db.QueryRowContext(ctx, insertCustomTenantFlowField,
		arg.ID,
		arg.TenantID,
		arg.FieldKey,
		arg.Question,
		arg.IsRequired,
		arg.SortOrder,
	)
	var i InsertCustomTenantFlowFieldRow
	err := row.Scan(
		&i.ID,
		&i.FieldKey,
		&i.FieldType,
		&i.Question,
		&i.IsRequired,
		&i.IsEnabled,
		&i.SortOrder,
	)
	return i, err
}
