// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_flow_fields_find_by_tenant.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findAllTenantFlowFields = `-- name: FindAllTenantFlowFields :many
SELECT id,
       field_key,
       question,
       field_type,
       min_length,
       max_length,
       min_value,
       max_value,
       is_required,
       is_one_time,
       is_enabled,
       sort_order,
       created_at
FROM tenant_flow_fields
WHERE tenant_id = $1
ORDER BY sort_order, created_at
`

type FindAllTenantFlowFieldsRow struct {
	ID         uuid.UUID     `db:"id"`
	FieldKey   string        `db:"field_key"`
	Question   string        `db:"question"`
	FieldType  FlowFieldType `db:"field_type"`
	MinLength  sql.NullInt16 `db:"min_length"`
	MaxLength  sql.NullInt16 `db:"max_length"`
	MinValue   sql.NullInt32 `db:"min_value"`
	MaxValue   sql.NullInt32 `db:"max_value"`
	IsRequired bool          `db:"is_required"`
	IsOneTime  bool          `db:"is_one_time"`
	IsEnabled  bool          `db:"is_enabled"`
	SortOrder  int32         `db:"sort_order"`
	CreatedAt  time.Time     `db:"created_at"`
}

// FindAllTenantFlowFields
//
//	SELECT id,
//	       field_key,
//	       question,
//	       field_type,
//	       min_length,
//	       max_length,
//	       min_value,
//	       max_value,
//	       is_required,
//	       is_one_time,
//	       is_enabled,
//	       sort_order,
//	       created_at
//	FROM tenant_flow_fields
//	WHERE tenant_id = $1
//	ORDER BY sort_order, created_at
func (q *Queries) FindAllTenantFlowFields(ctx context.Context, db DBTX, tenantID uuid.UUID) ([]FindAllTenantFlowFieldsRow, error) {
	rows, err := db.QueryContext(ctx, findAllTenantFlowFields, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllTenantFlowFieldsRow
	for rows.Next() {
		var i FindAllTenantFlowFieldsRow
		if err := rows.Scan(
			&i.ID,
			&i.FieldKey,
			&i.Question,
			&i.FieldType,
			&i.MinLength,
			&i.MaxLength,
			&i.MinValue,
			&i.MaxValue,
			&i.IsRequired,
			&i.IsOneTime,
			&i.IsEnabled,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
