// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: working_hours_insert.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertWorkingHour = `-- name: InsertWorkingHour :exec
INSERT INTO working_hours(
    id,
    resource_id,
    day_of_week,
    start_time,
    end_time,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertWorkingHourParams struct {
	ID         uuid.UUID `db:"id"`
	ResourceID uuid.UUID `db:"resource_id"`
	DayOfWeek  int16     `db:"day_of_week"`
	StartTime  time.Time `db:"start_time"`
	EndTime    time.Time `db:"end_time"`
	IsActive   bool      `db:"is_active"`
}

// InsertWorkingHour
//
//	INSERT INTO working_hours(
//	    id,
//	    resource_id,
//	    day_of_week,
//	    start_time,
//	    end_time,
//	    is_active
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6
//	)
func (q *Queries) InsertWorkingHour(ctx context.Context, db DBTX, arg InsertWorkingHourParams) error {
	_, err := db.ExecContext(ctx, insertWorkingHour,
		arg.ID,
		arg.ResourceID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.IsActive,
	)
	return err
}
