// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: working_hours_delete_by_resource.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkingHoursByResource = `-- name: DeleteWorkingHoursByResource :exec
DELETE
FROM working_hours
WHERE resource_id = $1
`

// DeleteWorkingHoursByResource
//
//	DELETE
//	FROM working_hours
//	WHERE resource_id = $1
func (q *Queries) DeleteWorkingHoursByResource(ctx context.Context, db DBTX, resourceID uuid.UUID) error {
	_, err := db.ExecContext(ctx, deleteWorkingHoursByResource, resourceID)
	return err
}
