load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "phone",
    srcs = ["phone.go"],
    importpath = "wappiz/pkg/phone",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/codes",
        "//pkg/fault",
    ],
)

go_test(
    name = "phone_test",
    srcs = ["phone_test.go"],
    embed = [":phone"],
    deps = ["@com_github_stretchr_testify//require"],
)
