load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "health_readiness",
    srcs = ["handler.go"],
    importpath = "wappiz/svc/api/routes/v1/health_readiness",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/logger",
        "@com_github_gin_gonic_gin//:gin",
    ],
)

go_test(
    name = "health_readiness_test",
    srcs = ["handler_test.go"],
    embed = [":health_readiness"],
    deps = [
        "//pkg/server",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_stretchr_testify//require",
    ],
)
