load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "webhookprocessor",
    srcs = [
        "interface.go",
        "service.go",
    ],
    importpath = "wappiz/internal/services/webhookprocessor",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/services/statemachine",
        "//pkg/buffer",
        "//pkg/counter",
        "//pkg/crypto",
        "//pkg/db",
        "//pkg/logger",
    ],
)

go_test(
    name = "webhookprocessor_test",
    srcs = ["service_test.go"],
    embed = [":webhookprocessor"],
    deps = [
        "//pkg/clock",
        "//pkg/counter",
        "@com_github_stretchr_testify//require",
    ],
)
