load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "booking",
    srcs = [
        "customer.go",
        "service.go",
    ],
    importpath = "wappiz/internal/services/booking",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/events",
        "//internal/services/plans",
        "//internal/services/slotfinder",
        "//pkg/codes",
        "//pkg/db",
        "//pkg/fault",
        "@com_github_google_uuid//:uuid",
        "@com_github_jackc_pgx_v5//pgconn",
    ],
)
